pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                bat 'python --version'
            }
        }
    }
    post  {
    	always {
	    echo "Cleaning up workspace"
	    deleteDir()
	}
    }
}
